<a href="https://colab.research.google.com/github/AbdurrahmanIdris/A-house-price-valuation-system-using-gradient-boosting/blob/master/A_house_price_valuation_system_using_gradient_boosting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import libraries**

In [0]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import ensemble
from sklearn.metrics import mean_absolute_error
import joblib

**Read DATA from CSV file and assign it to a data frame**

In [19]:
from google.colab import files
uploaded = files.upload()

Saving Melbourne_housing_FULL.csv to Melbourne_housing_FULL (2).csv

In [20]:
import io
df = pd.read_csv(io.BytesIO(uploaded['Melbourne_housing_FULL.csv']))
df.head(n=5)

       Suburb             Address  ...             Regionname Propertycount
0  Abbotsford       68 Studley St  ...  Northern Metropolitan        4019.0
1  Abbotsford        85 Turner St  ...  Northern Metropolitan        4019.0
2  Abbotsford     25 Bloomburg St  ...  Northern Metropolitan        4019.0
3  Abbotsford  18/659 Victoria St  ...  Northern Metropolitan        4019.0
4  Abbotsford        5 Charles St  ...  Northern Metropolitan        4019.0

[5 rows x 21 columns]

**Delete unneedeed columns** 
& **Remove rows with missing values**
& **Convert non-numerical data using one-hot encoding**

In [21]:
del df['Address']
del df['Method']
del df['SellerG']
del df['Date']
del df['Postcode']
del df['Latitude']
del df['Longitude']
del df['Regionname']
del df['Propertycount']

df.dropna(axis=0,how='any',thresh=None,subset=None,inplace=True)
features_df = pd.get_dummies(df,columns=['Suburb','CouncilArea','Type'])
del features_df['Price']
features_df.head(n=5)

    Rooms  Distance  Bedroom2  ...  Type_h  Type_t  Type_u
2       2       2.5       2.0  ...       1       0       0
4       3       2.5       3.0  ...       1       0       0
6       4       2.5       3.0  ...       1       0       0
11      3       2.5       4.0  ...       1       0       0
14      2       2.5       2.0  ...       1       0       0

[5 rows x 359 columns]

**Create X and Y arrays from the dataset**

---
**Split data into test/train set (70/30 split) and shuffle**

In [22]:
X = features_df.as_matrix()
Y = df['Price'].as_matrix()
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.

**Set up algorithm**

---
**Run model on training data**

---
**Save model to file**

In [28]:
model = ensemble.GradientBoostingRegressor(
n_estimators=250,
learning_rate=0.1,
max_depth=5,
min_samples_split=4,
min_samples_leaf=6,
max_features=0.6,
loss='huber'
)

model.fit(X_train, Y_train)

joblib.dump(model, 'house_trained_model.pkl')

mse = mean_absolute_error(Y_train, model.predict(X_train))
print ("Training Set Mean Absolute Error: %.2f" % mse)

mse = mean_absolute_error(Y_test, model.predict(X_test))
print ("Test Set Mean Absolute Error: %.2f" % mse)

Training Set Mean Absolute Error: 123685.93
Test Set Mean Absolute Error: 157676.50